platform :ios, "8.0"

target 'YReaderDemo' do
#use_framework!
pod 'AFNetworking'
pod 'SDWebImage'
pod 'YYCache'
pod 'YYModel'
pod 'YYCategories'
pod 'CocoaLumberjack'
pod 'MJRefresh'
pod 'MBProgressHUD'


end
