platform :ios, "8.0"

target 'YReaderDemo' do
#use_framework!
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.0'
pod 'YYCache', '~> 1.0.0'
pod 'YYModel', '~> 1.0.0'
pod 'YYImage', '~> 1.0.0'
pod 'YYCategories', '~> 1.0.0'
pod 'CocoaLumberjack', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.10'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Bugly', '~> 2.4.6'
#pod 'JSPatch', '~> 1.1.3'
pod 'IQKeyboardManager', '~>4.0.8'

# 主模块(必须)
pod 'ShareSDK3',:git => ‘https://github.com/MobClub/ShareSDK-for-iOS-Spec.git'

pod 'MOBFoundation_IDFA’
# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'ShareSDK3/ShareSDKUI',:git => ‘https://github.com/MobClub/ShareSDK-for-iOS-Spec.git'

pod 'ShareSDK3/ShareSDKPlatforms/QQ',:git => ‘https://github.com/MobClub/ShareSDK-for-iOS-Spec.git'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo',:git => ‘https://github.com/MobClub/ShareSDK-for-iOS-Spec.git'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat',:git => ‘https://github.com/MobClub/ShareSDK-for-iOS-Spec.git'

# 使用配置文件分享模块（非必需）
pod 'ShareSDK3/ShareSDKConfigurationFile',:git => ‘https://github.com/MobClub/ShareSDK-for-iOS-Spec.git'

# 扩展模块（非必需）
pod 'ShareSDK3/ShareSDKExtension',:git => ‘https://github.com/MobClub/ShareSDK-for-iOS-Spec.git'


end
